quarkus:
  swagger-ui:
    always-include: true
    path: /swagger
  smallrye-openapi:
    store-schema-directory: ./src/main/resources/apis
    info-title: Event-Ease API
    info-version: 1.0.0
    info-description: Seamlessly manage any event quickly and easily with our versatile SaaS platform. Perfect for any occasion.
    info-terms-of-service: Your terms here
    info-contact-email: coralo.luca@outlook.com
    info-contact-name: Example API Support
    info-contact-url: http://exampleurl.com/contact
    info-license-name: MIT License
    info-license-url: https://opensource.org/license/mit